name: example
description: Exemplo de uso do pacote widgets_package.
publish_to: 'none' # Evita que o exemplo seja enviado ao pub.dev

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

  widgets_package:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
